[[redirects]]
  from = "/adventures"
  to = "/https://ifoundtheme.substack.com"
  status = 302

[[redirects]]
  from = "/blog"
  to = "/https://ifoundtheme.substack.com"
  status = 302

[[redirects]]
  from = "/blog"
  to = "https://frijol.gitbooks.io/orienteering-software-tutorials/content/"
  status = 302