[[redirects]]
  from = "/adventures"
  to = "https://ifoundtheme.substack.com"
  status = 302

[[redirects]]
  from = "/blog"
  to = "https://ifoundtheme.substack.com"
  status = 302

[[redirects]]
  from = "/oom"
  to = "https://kelsey.gitbook.io/orienteering-software-tutorials/"
  status = 302